version: "3.3"
services:
  filebeat:
    image: elastic/filebeat:8.12.2
    container_name: filebeat
    volumes:
      - type: bind
        source: ${PWD}/filebeat_test.yaml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ${PWD}/logs
        target: /my_logs
    depends_on:
      - elasticsearch
    restart: no
  logstash:
    image: logstash:8.12.2
    container_name: logstash
    ports:
    - "5044:5044"
    volumes:
      - type: bind
        source: ${PWD}/logstash_test.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: no
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    restart: no
  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: no
